### ISSUE TITLE
Add Initial Content

### ISSUE THREAD

**Issue by alejandroblandon** [csctd/profile-website-alejandroblandon#4]
- [ ] Projects
- [ ] Social Media/Contact Infor
- [ ] More pictures
- [ ] Hobbies

**Comment by brownsarahm** [comment]
can you add your site map?

**Comment by alejandroblandon** [comment]
![Site Map](https://github.com/csctd/profile-website-alejandroblandon/assets/141266040/4e576af1-320d-4cc1-af91-b084ec7435ee)

**Comment by sarmenti7** [comment]
Nice work! Will you include your pictures and hobbies on the home page? Or, would you create separate pages for them on your site?
