### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by alejandroblandon** [csctd/profile-website-alejandroblandon#5]
- [ ] Cool animations like fades and slides
- [ ] accessibility
- [ ] interactivity

**Comment by alejandroblandon** [comment]
![Wireframe](https://github.com/csctd/profile-website-alejandroblandon/assets/141266040/3ac4e52d-4534-4a6f-b270-3c5e6f82599c)

**Comment by sarmenti7** [comment]
Perfect!
